spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8071
      fail-fast: true

  config:
    import: "configserver:"

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.optimagrowth: DEBUG