spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8071
      fail-fast: true
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

  config:
    import: "configserver:"

