server:
  port: 8072

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: organization-service
              uri: lb://organization-ms
              predicates:
                - Path=/organization/**
              filters:
                - RewritePath=/organization/(?<path>.*), /$\{path}

management:
  endpoint:
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include: gateway