services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: license_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    networks:
      - microservices-net
    volumes:
      - postgres-volume:/data/postgres
    restart: unless-stopped

  vault:
    image: vault:1.13.3
    container_name: vault-container
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200

  config-server:
    image: danilchet/config-server-ms
    container_name: config-server-container
    ports:
      - "8071:8071"
    networks:
      - microservices-net
    depends_on:
      - postgres

  license-ms:
    image: danilchet/license-ms
    container_name: license-ms-container
    ports:
      - "8080:8080"
    networks:
      - microservices-net
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8071
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
    depends_on:
      - postgres
      - config-server

networks:
  microservices-net:
    driver: bridge
volumes:
  postgres-volume: