services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    networks:
      - microservices-net
    volumes:
      - postgres-volume:/data/postgres
    restart: unless-stopped

  config-server:
    image: danilchet/config-server-ms
    container_name: config-server-container
    ports:
      - "8071:8071"
    networks:
      - microservices-net
    depends_on:
      - postgres

  o-stock:
    image: danilchet/o-stock-ms
    container_name: o-stock-container
    ports:
      - "8080:8080"
    networks:
      - microservices-net
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8071
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
    depends_on:
      - postgres
      - config-server

networks:
  microservices-net:
    driver: bridge
volumes:
  postgres-volume: