spring:
  application:
    name: organization-ms
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8071
      fail-fast: true
  config:
    import: "configserver:"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8300/realms/spima-realm
          jwk-set-uri: http://localhost:8300/realms/spima-realm/protocol/openid-connect/certs

keycloak:
  realm: spima-realm
  auth-server-url: http://localhost:8300/auth
  ssl-required: external
  resource: ostock
  credentials:
    secret: TAUsQhK3sSV4wTOrf31s3lUzpAq9p9lg
  use-resource-role-mappings: true
  bearer-only: true