@path = http://localhost:8081/v1/organization

### GET request to example server
GET {{path}}/b67f7327-eeae-4534-aab3-67f80cfb9ac6

### POST request to example server
POST {{path}}
Content-Type: application/json

{
  "name": "Test",
  "contactName": "Test",
  "contactEmail": "Test",
  "contactPhone": "Test"
}