spring:
  application:
    name: o-stock
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8071
  config:
    import: "configserver:"

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
    default-schema: license_schema
    liquibase-schema: public

server:
  port: 8080


