spring:
  application:
    name: license-ms
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8071
      fail-fast: true
    stream:
      bindings:
        mySource-in-0:
          destination: test-topic
          group: my-consumer-group
      kafka:
        binder:
          brokers: localhost:9092
          producer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer  # Десериализатор JSON
            spring.json.trusted.packages: "*"  # Разрешаем десериализацию любых классов (можно указать конкретный пакет)
            spring.json.value.default.type: ru.danil.algos.ostock.kafkaTest.model
  config:
    import: "configserver:"

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
logging:
  level:
    ru.danil.algos.ostock: DEBUG

