example:
  property: I AM THE DEV

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/organization_db?currentSchema=organization_schema
    username: postgres
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8300/realms/spima-realm
          jwk-set-uri: http://localhost:8300/realms/spima-realm/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/