example:
  property: I AM DOCKER

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/organization_db?currentSchema=organization_schema
    username: postgres
    password: root

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://vault:8300/realms/spima-realm
          jwk-set-uri: http://vault:8300/realms/spima-realm/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      default-zone: http://eureka-server:8761/eureka/