spring:
  application:
    name: config-server
  profiles:
    active:
    - native, git

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/
        git:
          uri:
          search-paths:

server:
  port: 8071
