spring:
  application:
    name: config-server
  profiles:
    active: vault, git

  cloud:
    config:
      server:
        vault:
          host: localhost
          kv-version: 2
          token: myroot
        git:
          uri: https://github.com/DanyaChetvyrtov/microservices-in-action.git
          search-paths: configurations/{application}

server:
  port: 8071
