example:
  property: I AM DOCKER

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/license_db?currentSchema=license_schema
    username: postgres
    password: root

eureka:
  client:
    service-url:
      default-zone: http://eureka-server:8761/eureka/