example:
  property: I AM THE DEV

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/license_db?currentSchema=license_schema
    username: postgres
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
