example:
  property: I AM DOCKER

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/license_db?currentSchema=license_schema
    username: postgres
    password: root

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/spima-realm
          jwk-set-uri: http://keycloak:8080/realms/spima-realm/protocol/openid-connect/certs

eureka:
  instance:
    prefer-ip-address: false
  client:
    serviceUrl:
      default-zone: http://eureka-server:8761/eureka/