example:
  property: I AM THE DEFAULT

spring:
  jpa:
    hibernate:
      ddl-auto: validate # Безопаснее, чем 'none'
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080