example:
  property: I AM THE DEV

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/license_db?currentSchema=license_schema
    username: postgres
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1

  sql:
    init:
      schema-locations: classpath:/sql/schema.sql # папку храню в resources
      mode: always

  jpa:
#    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: license_schema
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8300/realms/spima-realm
          jwk-set-uri: http://localhost:8300/realms/spima-realm/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/